# Copyright 2014 Keith Batesole
#  
# Purpose of file is to plot the cost of the slope
# gradients generated by a .c file

set key outside
set title "Slope Cost"
set xlabel "Slope Gradient"
set ylabel "Cost J/kg*m"
set grid front
plot "slope_cost.dat" u 1:2 w lines lt rgb "green"